apiVersion: apps/v1
kind: Deployment
metadata:
  name: evofast-authservice
  labels:
    app: evofast-authservice
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: evofast-authservice
  template:
    metadata:
      labels:
        app: evofast-authservice
    spec:
      containers:
      - name: evofast-authservice
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        envFrom:
        - configMapRef:
            name: evofast-authservice-config
        - secretRef:
            name: evofast-authservice-secret
