apiVersion: v1
kind: Secret
metadata:
  name: evofast-authservice-secret
type: Opaque
stringData:
  ConnectionStrings__Database: {{ .Values.secrets.dbConnection | quote }}
  ConnectionStrings__DatabaseHangfire: {{ .Values.secrets.dbHangfire | quote }}
  MessageBroker__Host: {{ .Values.secrets.brokerHost | quote }}
  MessageBroker__UserName: {{ .Values.secrets.brokerUsername | quote }}
  MessageBroker__Password: {{ .Values.secrets.brokerPassword | quote }}
